### ISSUE TITLE
Cannot get summary of psem model, error "undefined columns selected"

### ISSUE THREAD

**Issue by sweetmoniker** [jslefche/piecewiseSEM#165]
First of all, thanks so much for this package. I am making a structural equation model with binomial data. The model will calculate accurately, and I can see the resulting data frame listed under "data" in R Console. However, I am unable to run summary([psem model]) on it. Doing so results in the error "Error in `[.data.frame`(data, , vars) : undefined columns selected". I can View([psem model]), but I cannot get the summary to go to the console. Below is 100 observations of the dependent variable and an independent variable which still results in the error. 

y = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)

x = c(1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0)

psem.model = psem(glm(y ~ x, family = binomial()))

summary(psem.model)
Error in `[.data.frame`(data, , vars) : undefined columns selected

Is there something I'm missing? Any insight? Thanks!

**Comment by jslefche** [comment]
Hmm, its possible you caught a bad commit that I’ve since fixed, as it does work now. Try updating from Github again and see if it persists.

FYI psem does require a data argument, I get an error using the example you provided which stores x and y as separate objects in the local environment

HTH

____________________________
Jonathan S. Lefcheck, Ph.D.
Coordinating Scientist, MarineGEO
Smithsonian Institution
https://marinegeo.si.edu/
Phone: +1 (443) 482-2443
https://jonlefcheck.net/

**Comment by sweetmoniker** [comment]
I see what you mean about requiring a data frame. Regardless, I found what was causing the issue. When defining a model, I had always written

psem.model = psem(glm(y ~ data_frame$x, family = binomial(), data = data_frame)) 

Removing "data_frame$" preceding the independent variables solved the problem. Thanks.
