### ISSUE TITLE
Error: Unsupported family.

### ISSUE THREAD

**Issue by RaqVig** [jslefche/piecewiseSEM#170]
Hi,
I get the error: unsupported family, when trying to run summary function. 

The model is:
modelo1_doc =psem(
  glmmPQL(DOC_mgm.2 ~ Moisture_core_1 + temp + root_biom_transf + microbialbiomass_core + Acari_biomasa_totales_met + Collembola_biomasa_totales_met, ~1|Sampling, 
  family = gaussian(link = "log"), na.action = na.exclude, data = relationships, verbose = FALSE),
)

Anybody knows what's happening?

Thank you in advance,
Raquel

**Comment by jslefche** [comment]
Hi Raquel…that’s strange as glmmPQL should be supported. I will look into this and get back to you soon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by RaqVig** [comment]
Thank you, Jon.
I would appreciate that you let me know if it can be fixed.

Raquel

**Comment by jslefche** [comment]
Hi Raquel, this was an issue with the `rsquared` function and has since been fixed. Please reinstall from Github, re-run the code, and let me know if it persists!
____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by RaqVig** [comment]
Now it does work. Thank you very much!
