### ISSUE TITLE
cannot calculate AICc values for GLMs

### ISSUE THREAD

**Issue by srgriffin108** [jslefche/piecewiseSEM#180]
In piecewiseSEM 2.0 I'm using intermediate endogenous variables that are non-normally distributed, and (as expected) receive the error: "Non-linearities detected in the basis set where P-values are not symmetrical. This can bias the outcome of the tests of directed separation." 

I can get past this with the summary function by using conserve=T, but the summary only includes AIC and BIC, not AICc. When I use the AIC function (AIC(full_modlist, aicc = TRUE)), I receive the same error as above and cannot calculate AICc values. 

Any thoughts or solutions would be much appreciated!

**Comment by jslefche** [comment]
Hi Sean,

That is tricky. You can store the summary output as an object and extract the AICc score from that:

out <- summary(modelList, conserve = T)

out$IC

Its not clear to me yet how to fix the AIC function to inherit arguments from `summary` due to the way R handles S3 methods. Will think on that

J

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
should be resolved in new implementation of `AIC`
