### ISSUE TITLE
Discordant AIC of psem output and Shipley (2013) description

### ISSUE THREAD

**Issue by Matthew-Holding** [jslefche/piecewiseSEM#207]
Hello,

I was attempting to fully understand the AIC output of a summary(psem(model)) call by looking back at the description in Shipley (2013), and I cannot come up with the same answer using the two. Take the keeley example data as a demonstration, which is laid out in [this tutorial](https://jslefche.github.io/sem_book/local-estimation.html) : 

keeley_psem <- psem(
  lm(firesev ~ age, data = keeley),
  lm(cover ~ firesev, data = keeley),
  data = keeley)

AIC(keeley_psem)
17.18

According to summary(keeley_psem), Fisher's C = 5.18

So, solving AIC = C + 2K, we get K = 6. 

But, attempting to derive K using Shipley 2013 (reference his Table 2 in particular), I get K = 5 by looking at the model graph and considering free-parameter number:

cover = firesev + error                   >>>> 2 free params
firesev = age + error                      >>>> 2 free params
age = error                                      >>>> 1 free param

Could someone please help me understand what I am missing in terms of the calculation of the K value? 

Thank you so much!

![Rplot01](https://user-images.githubusercontent.com/32144511/83653418-c3111280-a589-11ea-8998-98afb5511c2d.png)

**Comment by jslefche** [comment]
Hmm this is very puzzling; there might be an error in the paper, or I might be missing something

So, K is the likelihood degrees of freedom (number of parameters estimated using likelihood).

Let’s then just take the first submodel in the Fig1 of Shipley’s 2013 paper: x2 ~ x1

For this you are estimating: the slope, the intercept, and error variance, So K = 3

This is what is returned if you look at the df from the `logLik` function

But Shipley suggests it is just K = 2 estimated parameters, slope and error. Since this is the minimum information needed to execute the d-sep tests (not intercept)

In the Appendix B, however, for the mixed effects implementation, he asserts the parameters estimated are: (1) fixed intercept, (2) fixed slope, (3) random intercept, (4) random slope; (5) correlation between random intercepts and fixed effect of x2 ; (6) error variance. So K= 6, which is what logLik returns

So not sure of the discrepancy…will look into it and follow up



____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
Some code

```
simulated.data <- read.table("http://www.esapubs.org/archive/ecol/E094/047/simulated.data.txt")

lm.mod <- lm(x2 ~ x1, data = simulated.data)

attr(logLik(lm.mod), "df")


lmer.mod <- lmer(x2 ~ x1 + (x1|species),data=simulated.data)

attr(logLik(lmer.mod), "df")
```

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
In local estimation there is no estimate of the variance on exogenous predictors so that wouldn’t be included. There would also not be an intercept for the error since its residual variance (fitted – observed) and doesn’t require any additional parameters to be estimated.

I am still puzzling over why one would exclude intercepts in calculating the likelihood df . They are estimated regardless. I guess since they don’t factor into fisher’s C …but they do increase model complexity (more fixed effects, more intercepts—and that is compounded for random effects). So the AIC should reflect that and be penalized appropriately.

For the record, I don’t think this affects model comparisons or Akaike weights, which is good.

I will let you know if I hear back from my colleagues on the topic – good catch! And good discussion



____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

**Comment by jslefche** [comment]
No longer an issue since new AIC function takes LL df directly from the models in the new formulation
