### ISSUE TITLE
Guide to how to add a new model type

### ISSUE THREAD

**Issue by jebyrnes** [jslefche/piecewiseSEM#219]
Can we write a guide and put in a vignette showing how to modify the package to add a new model type (e.g., glmmTMB, gam, etc.)? With a demo.

I've added one a few years back, but, have a hard time keeping track. HA!

It would be VERY helpful though, particularly as the mixed model world continues to evolve rapidly. 

Could start with just a list of what functions that need to be modified, and even a bit easier if we have what each function will need and/or an example.

**Comment by jslefche** [comment]
My hope is to get glmmTMB and GAMs in there this week

It’s a bit more difficult because several functions are called to each model type: `coefs` `rsquared` being the two main ones that require a LOT of tweaks to accommodate

Let me think on this

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>
