### ISSUE TITLE
Using piecewiseSEM  for prediction of future scenarios

### ISSUE THREAD

**Issue by PedroHLebre** [jslefche/piecewiseSEM#245]
Hello 

I apologize is my question is quite basic, I'm new to SEM and still learning. I have used piecewiseSEM to construct a model with climatic variables and would like to use it to predict the values of the response variables if the exogenous variables change over time. However, I'm not sure how to do this and would greatly appreciate any guidance .  The only reference to a method I found is psem.predict(), which is not a function in the newer versions of piecewiseSEM. Should I then use the predict() function to estimate the values of each endogenous variable and response variable? 

Thank you very much for the help. 

Cheers
Pedro

**Comment by jslefche** [comment]
Hi Pedro, prediction is not yet possible with the package. It would be possible to use the predict function for the individual models if the two variables are directly adjacent. Otherwise you will have to devise a way to propagate error through the network

Cheers,

Jon

____________________________
Jonathan S. Lefcheck, Ph.D.
Tennenbaum Coordinating Scientist
MarineGEO: https://marinegeo.si.edu/
Smithsonian Institution
Phone: +1 (443) 482-2443
www.jonlefcheck.net<http://www.jonlefcheck.net>

From: ***@***.***>
Sent: Wednesday, December 8, 2021 4:44 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [jslefche/piecewiseSEM] Using piecewiseSEM for prediction of future scenarios (Issue #245)

External Email - Exercise Caution

Hello

I apologize is my question is quite basic, I'm new to SEM and still learning. I have used piecewiseSEM to construct a model with climatic variables and would like to use it to predict the values of the response variables if the exogenous variables change over time. However, I'm not sure how to do this and would greatly appreciate any guidance . The only reference to a method I found is psem.predict(), which is not a function in the newer versions of piecewiseSEM. Should I then use the predict() function to estimate the values of each endogenous variable and response variable?

Thank you very much for the help.

Cheers
Pedro

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjslefche%2FpiecewiseSEM%2Fissues%2F245&data=04%7C01%7Clefcheckj%40si.edu%7C01a90ea8b04b400836cf08d9ba2f4745%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637745534487736022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=0Vsa4qa1syb8Gf0Atg4thulnZh5EXlCjOTkYkeJYPjc%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAR4AVYRCKOFY66YI4ZO3MTUP4SGNANCNFSM5JTLBLLQ&data=04%7C01%7Clefcheckj%40si.edu%7C01a90ea8b04b400836cf08d9ba2f4745%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637745534487736022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=8RRmQkhp0ORcVb1E6wO3Qjt%2F7j7fwyUVQcRx0hWOdig%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Clefcheckj%40si.edu%7C01a90ea8b04b400836cf08d9ba2f4745%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637745534487745979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6fqIBxGd8Ujwg8FVVG7iiyN7hzVZT99Odf1Vphpcdkk%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Clefcheckj%40si.edu%7C01a90ea8b04b400836cf08d9ba2f4745%7C989b5e2a14e44efe93b78cdd5fc5d11c%7C0%7C0%7C637745534487745979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=p63NR1KyvlYvOBePjoHZqc%2Ban8Hu%2BOLJVyk46eLzyo0%3D&reserved=0>.
