### ISSUE TITLE
Throw more descriptive error when dealing with factorial variables

### ISSUE THREAD

**Issue by jslefche** [jslefche/piecewiseSEM#75]

**Comment by jslefche** [comment]
@jebyrnes how should we return coefficients from categorical variables?

**Comment by jebyrnes** [comment]
Hrm. Well, the default would be to gak the coefficients from the summary table, and the user would be left dealing with whether or not this was a treatment of non-intercept contrast table.

It's not a perfect solution, but it's functional. Perhaps if an intercept is included, throw an error about the lack of meaning of std coefs for factors. If the intercept is removed, then we can report range-standardized standardized coefs? The issue is, only range standardization is meaningful for factors. As the range is always 0.5. Otherwise, things get squirrely and depend on number of treatments, balance, etc., which makes no sense.
