### ISSUE TITLE
error while extracting Coefs due to getData function in line 11

### ISSUE THREAD

**Issue by bsercu** [jslefche/piecewiseSEM#95]
Dear Mr. Lefcheck,

My collaborator posted an original error on [stackoverflow](http://stackoverflow.com/questions/43350715/extracting-path-coefficients-of-piecewise-sem-structural-equation-model#comment73774074_43350715)

The error was induced by NA values in our dataset. When removing the NA's we can extract coefficients in both versions of piecewiseSEM.

While we are able to continue now by removing the NA's it might be helpfull for you to know we were stuck for a moment on this issue.

We tried using the version 2.0 as you proposed however this also throws an error when using the Coefs function.
"Error in data.frame(..., check.names = FALSE) : arguments imply differing number of rows: 81, 76"
I was able to trace the error back to line 11.
more specifically "getData.(modelList)" generates the error due to NA's in our dataset

I tested the function and while the getData command works fine for every single model it throws the error when applying to the list of models.

I attached our datafile and a notebook with the code I used for debugging

[debug.zip](https://github.com/jslefche/piecewiseSEM/files/916239/debug.zip)

**Comment by jslefche** [comment]
Hi Bram- it may not be appropriate to run the component models on datasets of different sizes, particularly if you are interested in computing indirect effects. I recommend removing rows with `NA` for all variables in the SEM, and you should have no problem with the function. I will flag this issue since `piecewiseSEM` should throw a `stop` when datasets are of different sizes.
